version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  app-node:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=mubbaseer
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
      
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mubbaseer
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
