version: '3'
services:
  app-node:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    ports:
      - 3000:${PORT}
    